sudo: required
services:
  - docker

before_install:
  - docker build -t fatems/react-front-docker -f Dockerfile.dev .

script:
  - docker run fatems/react-front-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-2"
  app: "react-front-docker"
  env: "Docker-env"
  bucket-name:  "elasticbeanstalk-us-west-2-306476627547"
  bucket-path: "react-front-docker"
  on
    branch: "main"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    